name: Actualizador 24-7
on:
  schedule:
    - cron: '*/10 * * * *' # Se ejecuta cada 10 minutos
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar yt-dlp
        run: |
          python3 -m pip install -U yt-dlp

      - name: Ejecutar Script de Python
        run: python3 update.py

      - name: Guardar cambios y subir
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@github.com"
          git add latribu.m3u8
          git commit -m "Update HLS Link" || exit 0
          git push
